/*
************************************************************************
Compile Switches
************************************************************************
*/


/*
************************************************************************
Include Files
************************************************************************
*/

/*  Include config.h generated by automake/autoconf if present  */
#if HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

/*  GNU readline functions (for input editting)  */
#ifdef HAVE_LIBREADLINE
#include <readline/readline.h>
#include <readline/history.h>
#endif

#include "parse.h"



/*
************************************************************************
Macros
************************************************************************
*/

#define NO_ERROR 0

#define TRUE 1
#define FALSE 0


#define NBUF 1024



/*
************************************************************************
Local Function Prototypes
************************************************************************
*/
void PrintNumber (double);
void PrintHelp (void);
void PrintGreeting (void);
void ListVariables (void);



/*
************************************************************************
Module-Wide Variables
************************************************************************
*/

/*  LIST OF FUNCTIONS  */
char *FunctionNames_m[] = {
   "sin", "cos", "tan", "exp", "log", "log10", "abs",
   "sqrt", "acos", "asin", "atan", NULL
};



/*
************************************************************************
Main Function
************************************************************************
*/

#pragma argsused
main (int argc, char *argv[]) {
   double Result;
   char *InputString;
   char *InputStringPtr;
   char *ErrorMessage;
   char TokenBuffer[80];
   char *TokenPtr;
   int Continue;
   int ErrorCode;
#ifndef HAVE_LIBREADLINE
	char InputBuf[NBUF];
#endif

   /*  Print greeting  */
   PrintGreeting ();

   /*  Read line input  */
   Continue = TRUE;
   while (Continue) {

		/*  Read until we get a non-blank line  */
		do {
#ifdef HAVE_LIBREADLINE
			InputString = readline ("calc> ");
#else
			fputs ("calc> ", stdout);
			InputString = fgets (InputBuf, NBUF, stdin);
			/*  2007-10-20 - Need following to prevent 'segmentation error'
			 *  when ending the program with CTRL-D  */
			if (InputString) InputString[strlen(InputString)-1] = '\0';
#endif
			if (NULL == InputString) {
				printf("\n");
				return(0);
			}
		} while (!strcmp ("", InputString));

		/*  PASS FIRST SPACES  */
		InputStringPtr = InputString;

		while (*InputStringPtr == ' ')
			InputStringPtr++;

		/*  COPY NON-BLANK CHARACTERS  */
		TokenPtr = TokenBuffer;
		while (!isspace (*InputStringPtr) && *InputStringPtr != 0)
			*(TokenPtr++) = toupper (*(InputStringPtr++));
		*TokenPtr = 0;

		/*  TEST TOKEN  */
		/*  Skip comments (beginning with #)   */
		if (IsComment (TokenBuffer, "#")) {
			/*  Do nothing  */
		} else if (!strcmp (TokenBuffer, "HELP")) {
			  PrintHelp ();
		} else if (!strcmp (TokenBuffer, "LIST")) {
			  ListVariables ();
		} else if (!strcmp (TokenBuffer, "QUIT")) {
			Continue = FALSE;

		/*  Arithmetic expression entered  */
		} else {

#ifdef HAVE_LIBREADLINE
			/*  Save expression in history  */
			add_history (InputString);
#endif

			InputStringPtr = InputString;
			Result = evalform (&InputStringPtr, &ErrorCode);
			if (ErrorCode == NO_ERROR) {
				PrintNumber (Result);
				printf ("\n\n");
				fflush (stdout);
				/*  Store this result as special variable %  */
				AssignVariable ("%", Result);

			/*  Error message  */
			} else {
				  ErrorMessage = parsemsg (ErrorCode);
				  if (ErrorMessage == NULL)
					  printf ("Unknown error.\n\n");
				  else
					  printf ("%s\n\n", ErrorMessage);
				  fflush (stdout);
			}
		}
	}
	return (0);
}

/*
************************************************************************
Local Functions
************************************************************************
*/

void
PrintNumber (double Value)
{
   if (fabs (Value) < 1.0e-4)
      printf ("%e", Value);

   else if (fabs (Value) > 1.0e4)
      printf ("%e", Value);

   else
      printf ("%f", Value);
}


void
PrintHelp (void)
{
   int ifunc;

   printf ("\n");
   printf ("CALC    A Simple Calculator\n");
   printf ("---------------------------\n");
   printf ("\n");
   printf ("   LIST - list current variables.\n");
   printf ("   QUIT - end program.\n");
   printf ("\n");
   printf ("   BUILT-IN FUNCTIONS\n");
   ifunc = 0;
   while (FunctionNames_m[ifunc] != NULL)
     {
	if (ifunc % 8 == 0)
	   printf ("   ");
	printf ("%-8s", FunctionNames_m[ifunc]);
	ifunc++;
	if (ifunc % 8 == 0)
	   printf ("\n");
     }
   if (ifunc % 8 != 0)
      printf ("\n");

   printf ("\n");
   printf ("   OPERATORS AND SYMBOLS\n");
   printf ("      + - * / ^ ( ) =    Mathematical operators\n");
   printf ("      %%                  Stands for previous result\n");
   printf ("      %%PI %%E             Constants pi and e\n");
   printf ("      (variables)        Up to 128 of them\n");


   printf ("\n");
   printf ("   EXAMPLE\n");
   printf ("      calc> x = 5\n");
   printf ("         x = 5.000000\n");
   printf ("      calc> 5*x^2\n");
   printf ("         x = 125.000000\n");
   printf ("      calc> (%% + 5) / 5\n");
   printf ("         25.000000\n");
   printf ("      calc> cos(%%pi/4)\n");
   printf ("         0.707107\n");
   printf ("      calc> exp(1.7)\n");
   printf ("         5.473947\n");
   printf ("      calc> %%e^1.7\n");
   printf ("         5.473947\n");
   printf ("\n");
   fflush (stdout);
}

void
ListVariables (void)
{
   int ivar;
   char *VariableName;
   double VariableValue;

   printf ("CURRENT VARIABLES\n");
   ivar = 0;
   while ((VariableName = listvar (ivar++, &VariableValue)) != NULL)
     {
	printf ("   %s ", VariableName);
	PrintNumber (VariableValue);
	printf ("\n");
     }
   printf ("\n");
   fflush (stdout);
}

void
PrintGreeting (void)
{
   printf ("\n");
   printf ("                 **********************************\n");
   printf ("                 *  CALC - The Simple Calculator  *\n");
   printf ("                 **********************************\n");
   printf ("\n");
   printf ("Type HELP for help.\n");
   printf ("\n");
   fflush (stdout);
}



/*
************************************************************************
String Functions
************************************************************************
*/

int
IsWhiteSpace (char InputChar)
{
   return
      (InputChar == ' ' ||
       InputChar == '\n' ||
       InputChar == '\t' ||
       InputChar == '\r' ||
       InputChar == '\b' || InputChar == '\f' || InputChar == '\v');
}


void
SkipWhiteSpace (char **s)
{
   while (IsWhiteSpace (**s))
      (*s)++;
}


/*  Returns True if first non-whitespace characters is in string  */
int
IsComment (char *InputString, char *CommentChars)
{
   char LeadingChar;
   int TestIndex;

   /*  Find first non-white space character  */
   SkipWhiteSpace (&InputString);
   LeadingChar = InputString[0];


   /*  Scan list of comment characters to see if leading character belongs  */
   TestIndex = 0;
   while
      (CommentChars[TestIndex] != '\0' &&
       CommentChars[TestIndex] != LeadingChar)
      TestIndex++;

   /*  Return true if matching characters not string terminatore  */
   return CommentChars[TestIndex] != '\0';
}
